In [1]:
from BackgammonRLEnv import Env
from BackgammonModel import BackgammonModel

In [2]:
import torch
import random
import numpy as np

In [3]:
game = Env()

In [4]:
player, obs, actions, _ = game.reset()
assert game.game.cur_player.value == player
chosen_list = []
obs_list = [obs]
for i in range(10):
    chosen = actions[0]
    chosen_list.append(chosen)
    prev_player, prev_obs, prev_actions = player, obs, actions
    #player, obs, legal_actions, reward = 
    player, obs, actions, _ = game.step(chosen)
    obs_list.append(obs)
    #player, obs, actions, _ = game.step_back(chosen, prev_player)
    #assert prev_player == player
    #assert prev_obs == obs
    #print(game.game.turn_history[-1])
print('---UNDO---')
#print(game.game.turn_history)

for i in range(len(chosen_list)-1,-1,-1):
    chosen = chosen_list[i]
    prev_player, obs, actions, _ = game.step_back(chosen)
    assert (np.array(obs) == np.array(obs_list[i])).all()
    assert obs == obs_list[i]


Player 1 (white) rolled: 2
Player 2 (black) rolled: 2
Players rolled same numbers, rolling again...
Player 1 (white) rolled: 6
Player 2 (black) rolled: 3
Player 1 (white) goes first.
---UNDO---


In [5]:
obs = [float(o) for o in obs]
obs = torch.FloatTensor(obs)

In [6]:
a = actions[0]

In [7]:
model = BackgammonModel(198, 50, 1)

In [8]:
obs_list = []
for a in actions:
    _, obs, legal_actions, reward = game.step(a)
    obs_list.append(obs)
    _ = game.step_back(a)
print(len(obs_list))

38


In [9]:
game.agents[0].choose_best_action(actions)

486

In [10]:
out = model(torch.FloatTensor(obs_list))
print(out)

tensor([[0.5088],
        [0.5075],
        [0.5117],
        [0.5098],
        [0.5116],
        [0.5088],
        [0.5075],
        [0.5117],
        [0.5098],
        [0.5116],
        [0.5117],
        [0.5148],
        [0.5166],
        [0.5116],
        [0.5134],
        [0.5117],
        [0.5148],
        [0.5166],
        [0.5116],
        [0.5134],
        [0.5098],
        [0.5116],
        [0.5127],
        [0.5115],
        [0.5098],
        [0.5116],
        [0.5127],
        [0.5115],
        [0.5116],
        [0.5134],
        [0.5115],
        [0.5181],
        [0.5137],
        [0.5116],
        [0.5134],
        [0.5115],
        [0.5181],
        [0.5137]], grad_fn=<SigmoidBackward>)


In [31]:
model(torch.FloatTensor(obs)).backward()

In [33]:
for i,j in enumerate(list(model.parameters())):
    print(j.grad)
    print(j.shape)

tensor([[-0.0000e+00, -6.0811e-03, -0.0000e+00,  ..., -0.0000e+00,
         -0.0000e+00, -0.0000e+00],
        [-0.0000e+00, -5.0153e-03, -0.0000e+00,  ..., -0.0000e+00,
         -0.0000e+00, -0.0000e+00],
        [ 0.0000e+00,  8.3688e-04,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [-0.0000e+00, -6.9007e-03, -0.0000e+00,  ..., -0.0000e+00,
         -0.0000e+00, -0.0000e+00],
        [-0.0000e+00, -8.2806e-05, -0.0000e+00,  ..., -0.0000e+00,
         -0.0000e+00, -0.0000e+00],
        [ 0.0000e+00,  6.1024e-03,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])
torch.Size([50, 198])
tensor([-6.0811e-03, -5.0153e-03,  8.3688e-04, -1.3632e-03, -3.2388e-03,
        -3.4526e-03,  8.1014e-03, -8.4998e-03, -7.4729e-03, -3.9661e-03,
        -7.5794e-03,  7.3715e-03,  8.3652e-03, -7.7233e-03, -2.3664e-03,
         6.2565e-03, -1.0966e-03,  7.9414e-03, -9.2497e-04, -8.5037e-03,
        -7.9226e-03, -4.6776e-03,  8.0672e-03,  3.1146